### ISSUE TITLE
not automatically start pause countdown

### ISSUE THREAD

**Issue by me23** [Tranquility/pomodoromine#1]
Hi,

first of all, nice tool, thanks allot!

What do you think about not starting the countdown automatically after a pomodoro has
finished. Instead the countdown stops and we have two buttons for short break and
long break?

And may be you could measure the time for each ticked a have in the task-list and after i set it done only the time i used for this ticket will be logged to redmine. E.g. Sometimes I have a bunch of tiny tickets and 2 are done in one pomodoro then i want to click the first one, assume i need 5 minutes, a click at "mark done" and it logs 0,083 to redmine. Then i work on the second ticket which will take 15 minutes then 0,25 will be logged to redmine.

Greetings from Germany!
me23

**Comment by Tranquility** [comment]
Hey @me23, cool that you like it and thanks for your feature requests. 
In my first implementation I had the feature with the two buttons for short and long break. But then I realized two things:
1. I did not really stick to the 5 minutes, because I wasn't forced to.
2. My long breaks are really irregular ( between 20 minutes and 2 hours) so it doesn't make sense for me to use a timer.

Thats why I implemented the concept with set-size where you select how many pomodoros you want to make in a row and the short breaks are started and stopped automatically.

I like your second idea with more granular time tracking, that sounds really useful. When I started developing the application I thought the best way is to allow grouping of tasks, which would be closer to the idea of pomodoros, but your idea seams more practical. Should the actual time get tracked or percentages of 30 minutes? It also needs to be more transparent which ticket one is currently tracking the time for. What do you think?

**Comment by me23** [comment]
Hi Tranquility,

in my normal work day i have a lot of external interruptions by phone,
so after i finished one promodoro
i answer the phone calls. I don't know how long will it take,  so i have
to cancel the automatic break often.

For the second idea i would say actual time gets tracked, because i use
the time
in redmine for billing and statistics.

I would say the ticket you clicked on and of which the task discription
is shown will be tracked.
May be you could add an icon in the row of the current tracked task to
indicate that this one is be tracked?

But what happens if i have 3 tiny tasks in the task window and the
promodoro runs and i click/switch
to the other (may be a related ticket with addional information in task
description)?
Will the time goes to the first one until it is set done, or have each
task in list its own timetracking?

Another cool thing would be if i could get a list of open tickets, after
i have finished the pomodoro,
to decide which will be the next. So i don't have to switch to redmine
for that.

Oh and i have another idea just to make the life with redmine a little
easier: because of my external interruptions
i have to keep track whom to call back, or quickly add a new task. May
be we could have a button for enter a ticket
quick. Say only Project-Dropdown, Title, Description, Status alway as
"New", eventually the estimation field?!

**Comment by Tranquility** [comment]
Now we are discussing that many features at once that I doubt it's going to end well :wink: 
Could you open individual issues for each?  Lets concentrate on the start button in this one:

I can imagine a setting where you can select whether you want to start a new pomodoro automatically or not. If its not selected you need to press a button to start the next one in the current set. I don't think the break selection is needed, do you?

**Comment by me23** [comment]
You are absolutely right about the many features, i will open new
tickets for the other ideas... sorry

Ok if i disable the automatic the pomodoro ends and i have to press the
start button to the next one. And there
are no short break countdown? Then i will end in short breaks that lasts
one hour :-)

Do i understand the "setsize" feature right: if i choose "1" for set
size and the pomodoro finished, will the
break countdown run also or only if setsize is greater than 1? (to short
to test right know because the dinner
will be ready soon :-) )

If the break countdown also run, i don't have to disable the automatic,
because i could set it to 1, run the pomodoro, take the pause and at the
bell i can start a new one.

**Comment by Tranquility** [comment]
Basically all you said is true :-) After each pomodoro is a five minutes break that automatically starts and if you set the set-size to 1 you need to start a new pomodoro explicitly.
The only reason I see to have the manual option is to know when a long break makes sense and automatically start that one.

**Comment by me23** [comment]
Sorry i don't get that. You will start the long break automatically?

**Comment by Tranquility** [comment]
Yeah, for example if you select a set-size of 4 after 4 pomodoros the long break could automatically start and between the pomodoros a 5 minutes break.

**Comment by me23** [comment]
And for what do we need then manual option?

**Comment by Tranquility** [comment]
I thought you want to start the pomodoro manually because you sometimes need a longer break?

**Comment by me23** [comment]
Yes i wanted to start either the short or the longer break manually, but that was before the set size thing was clear
to me :-)
I can now easily adopt the work flow by setting it to 1 on weekdays (where the external interruptions are great) and
to 4 on weekends or in the evenings...

So i think it will give it i try, but i think it should work.

Thank you!

**Comment by Tranquility** [comment]
I will close this for now, please feel free to reopen it.
