### ISSUE TITLE
could not save icon as

### ISSUE THREAD

**Issue by me23** [Tranquility/pomodoromine#5]
Hi,

i'm running ubuntu 12.10 and start the application from terminal,
then i got following messages:
Could not save icon as '/tmp/sni-qt_pomodoromine_15842-jpbTcU/icons/hicolor/16x16/apps/pomodoromine_15842_1fd07571a5278bdba6564f8b47480a18.png'
Could not save icon as '/tmp/sni-qt_pomodoromine_15842-jpbTcU/icons/hicolor/22x22/apps/pomodoromine_15842_1fd07571a5278bdba6564f8b47480a18.png'
Could not save icon as '/tmp/sni-qt_pomodoromine_15842-jpbTcU/icons/hicolor/32x32/apps/pomodoromine_15842_1fd07571a5278bdba6564f8b47480a18.png'
Could not save icon as '/tmp/sni-qt_pomodoromine_15842-jpbTcU/icons/hicolor/48x48/apps/pomodoromine_15842_1fd07571a5278bdba6564f8b47480a18.png'

i installed the qt-sdk and make these steps to compile and run:

qmake-qt4 pomodoromine.pro
qmake-qt4
make
./pomodoromine

**Comment by me23** [comment]
Thanks a lot.

Should there be a Unity launscher icon?

**Comment by Tranquility** [comment]
No, ubuntu is not my primary distribution so I never cared about these things.
